# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano_inicial', models.IntegerField()),
                ('ano_final', models.IntegerField()),
                ('caminho', models.CharField(max_length=200)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machado.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=200)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machado.Obra')),
            ],
        ),
    ]
