# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='ano_final',
            new_name='ano',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='ano_inicial',
        ),
    ]
