# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machado', '0002_auto_20170301_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='nome_site',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
