# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machado', '0003_genero_nome_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='nome_site',
        ),
    ]
