# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machado', '0004_remove_genero_nome_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='nome_site',
            field=models.CharField(default='', max_length=30),
        ),
    ]
