# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machado', '0006_auto_20170310_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nome_site',
            field=models.CharField(max_length=30),
        ),
    ]
